name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - run: echo "Triggered by ${{github.event_name}} event"
    - uses: actions/checkout@v4
    - run: echo "The ${{github.repository}} repo has been cloned"
    - run: echo "Setting up JDK"
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - run : echo "The workflow is ready"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - run : echo "Building apk"
    - name: Build with Gradle
      run: ./gradlew build
    - run: echo "Build status - ${{job.status}}"
